### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by bcomnes** [netlify/gotrue#128]
Similar feature to what we have in Netlify. We need to track events in a new table and offer a UI for Netlify Site owners to see activity log. This is related to https://github.com/netlify/gotrue/pull/124, because that table should also use JSON to better indexing arbitrary data.

**Comment by rybit** [comment]
Ok I've been thinking about this and I think that we should definitely do something to detect/prevent tampering.

What I'm imagining is that we have something where for every entry we generate a public/private key pair, we then sign the line (e.g. generate a []byte, sha those, and encrypt with the private key)  that we are committing. We then update the next entry with that public key (creating the chain). 

meaning the schema would look something like this: 
```
| id | parent_key | signature | ........ all the other fields .....|
```

Then we would be also signing that we the parent key was used there. This would prevent tampering editing any entry would be detected by a signature change. This could easily also be a separate table that just ensured the validity of all the data. What is important is that we consistently hash all the data _including the parent key_ because that is how we ensure data integrity.

**Comment by brycekahle** [comment]
If you simply want to detect data modification, you only need to include the hash of the previous entry.

If you want to verify that a particular entry was written by an actor, then you need:
- a keypair that doesn't change for that actor
- the public key
- the entry needs to signed by the keypair

**Comment by calavera** [comment]
This is not about tampering data. The requirement is to write in a table who did what, without allowing external write access to that table.

The admin api should have only a readonly endpoint. Several endpoints in the code should generate an entry in the audit log:

- When a user gets invited.
- When there are change in user settings.
...

**Comment by rybit** [comment]
ok thinking about this I think that we should record:
(most of them are with a "actor" "action" "meta" after them)
- any modification to the user's settings
- user logs in user_a login ip
- user logs out: user_a logout ip
- instance created: system_user created_instance instance_id
- instance deleted: system_user deleted_instance instance_id

- user invite_accepted: user_B invite_accepted

// in these we would record the action like "user A invited user B" so the actor would be A
- user deleted: user_a deleted_user user_b
- user invited : user_a invited_user user_b
- user revoked: user_a revoked_user user_b <-- idk if this makes any sense

- auth token created: user_a created_token token_a
- auth token revoked: user_b revoked_token token_a
- auth token refreshed: user_a refreshed_token token_a

I think that we should consider a table with these fields:
- `timestamp`: epoch sec 
- `instance`: instance id
- `actor`: user id
- `action`: some enum of possible actions taken
- `meta`: free form data? Something showable in the UI? depends on the action? 
- `eventid`: the id of the row - monotonically increasing value (for unique & pagination) 

## api 
Then we'd have a single endpoint like 
```
GET /audit/<instanceid>[?actor=actor_id&action=<action>?limit=<#>?since=<utcsec>?last=<eventid>]
```
Essentially, we would scope the audit endpoint to per-instance and allow for filtering by action and actor. And we would support pagination. 

We would return a JSON blob looking like:
```
{
"instance_id":
"total_available": <number of events total>,
"total_remaining": <number of events older than the oldest here>,
"events": [
  {"id": "eventid", "actor": "actor_id", "name": "actor_name/email", "action": "actionenum", "meta": "freeformstring"},
]
}
```

### pagination
We should have the endpoint support some pagination. By default, we should return the last 50 events. But we should support the ability to scroll back through the log. I think just using a limit/last technique would be suitable. 

Meaning if you specify a limit (up to a certain value) we would respect it. Otherwise, we'd default to 50 (or something). And if you sent us `last=<#>` we would only search for events that are older than that one. 

## auth

We would have to verify that the requesting user has the right permissions in the JWT claims.

**Comment by calavera** [comment]
Sounds good, the path should be in the /instances resource that we already have, but it's a minor detail:

GET /instances/<instanceid>/audit

**Comment by brycekahle** [comment]
Who is requesting this audit data? UI via the API? If so, we get the instance id via the JWS the proxy adds. The path should probably be `GET /admin/audit` then, especially if you want to limit to admin users.

All the requests to the `/instances` endpoints are meant for operator/provisioning.

**Comment by calavera** [comment]
> Who is requesting this audit data? UI via the API?

Yes, UI via the API. I'm ok with an admin url too.

**Comment by bcomnes** [comment]
The account audit log shape looks like this:

```js
GET /api/v1/accounts/{account_id}/audit?page=1&per_page=50
```

We get back:  

Pagination header

```
link header: <https://api.netlify.com/api/v1/accounts/{account_id}/audit?page=2&per_page=50>; rel=next, <https://api.netlify.com/api/v1/accounts/{account_id}/audit?page=14&per_page=50>; rel=last
```

Response body

```
[
  {
    "id":"5a57eddb0b79b75496aadff8",
    "account_id":"58da8893d6865d35c92a72b8",
    "payload":{
      "actor_id":"590ba0eca700c44e7615960c",
      "actor_name":"Benaiah Mischenko",
      "actor_email":"ben+admin@netlify.com",
      "action":"Site Identity invites sent",
      "timestamp":"2018-01-11T23:06:03.586Z",
      "log_type":"site",
      "traits":{
        "site_id":"69350086-d20e-4b5a-84cf-bf367a848374",
        "site_subdomain":"www",
        "site_domain":"www.netlify.com",
        "service_id":"599eed0bcf321c08cfff1ae2",
        "service_slug":"identity",
        "service_name":"Netlify Identity"
      }
    }
  },
  ...
]
```

The payload is fairly open ended, but we group actions into categories based on `log_type` and switch on `action`, so I would say those are the two required fields.  Having `actor` information is also nice to have if you can associate an actor to the action.
