### ISSUE TITLE
Create hidden instance admin per site

### ISSUE THREAD

**Issue by bcomnes** [netlify/gotrue#130]
Create hidden instance admin per provisioned site in the API - Right now we use a global token. We should create a Netlify admin per service instance and prevent people from deleting them, via the UI and API.

**Comment by rybit** [comment]
We thought about doing this, or just making the first sign up to be admin and leaving it, but it is a bit complex. It makes the code nasty, and can lead to security holes. The other problem is that in the hosted solution we don't want to give admin privs to anyone because they can fall out of sync with the origin's version of things. It was decided that we didn't want the idea of a hidden admin because it was a larger pain than it was worth, and provided a security vulnerability (who does that recover with? How do we verify access? what if it leaks?)

**Comment by brycekahle** [comment]
Can we reformulate this as a problem? This is a prescribing a solution without mentioning why we need this, and what properties this particular solution gives us.

**Comment by calavera** [comment]
tokens are scoped by instance already, we don't need this.
