### ISSUE TITLE
Fix styling for Apple Mail

### ISSUE THREAD

**Issue by matthojo** [netlify/gotrue#350]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The emails are offset on Apple Mail

**- If the current behavior is a bug, please provide the steps to reproduce.**
View Identity emails in Apple Mail

**- What is the expected behavior?**
Add style="padding:0;" on the body element of Identity emails to fix the display issue on Apple Mail.

**- Please mention your Go version, and operating system version.**

Support issue: https://github.com/netlify/pillar-support/issues/461

**Comment by jackbrewer** [comment]
@matthojo Are you sure this is in the correct repo?

**Comment by matthojo** [comment]
@jackbrewer not at all 😄 I was informed this is the default repo for identity but unsure if it’s where the emails live.. sorry! Please feel free to move it if you know where it should live

**Comment by jackbrewer** [comment]
Slowly figuring it out. We are in the right repo… we just don't have a `body` element to add the padding to. For the default templates, this is the entire HTML payload which gets sent: 

<img width="525" alt="Screenshot 2023-07-28 at 10 37 11" src="https://github.com/netlify/gotrue/assets/720908/2ea5aa9e-5835-4338-837f-916672ababd2">

_(Verified in Apple Mail and Gmail)_

The HTML comes from here: https://github.com/netlify/gotrue/blob/3fabd3fc5a6fb51eb54cd88831a380a4c18a2eff/mailer/template.go#L17-L35

For a custom template, I'd guess the padding fix would need to be applied _within_ the custom template itself. We'll need to create a reproduction template with the alignment issue to verify.

**Comment by matthojo** [comment]
@jackbrewer These seems like _a lot_ of effort. Would you like to proceed, or shall we call this one a wontfix based on effort to problem.

**Comment by jackbrewer** [comment]
Had a quick play. We don't output a `<body>` element as part of the identity emails, so we're unable to add the `padding: 0`. We also recommend not to add one in a custom template on [our docs site](https://docs.netlify.com/visitor-access/identity/identity-generated-emails/#:~:text=Don%E2%80%99t%20include%20%3Chtml%3E%2C%20%3Chead%3E%2C%20or%20%3Cbody%3E%20tags%20in%20the%20template).

In testing, I found that without a body I could replicate the unwanted padding. If I ignored the docs advice and added one to my custom template, I could get rid of that problematic padding. I'd suggest this as a fix for this specific issue, but I don't have the additional context for why we advise otherwise, and what side-effects may be introduced across other email clients (👀  looking at you Outlook).

| No body element | body added within custom template |
|--------|--------|
|<img width="592" alt="image" src="https://github.com/netlify/gotrue/assets/720908/cf9f606c-35b6-43c5-afdc-227a9e4852ef">|<img width="601" alt="image" src="https://github.com/netlify/gotrue/assets/720908/e788af44-3db4-4a9d-b993-2ceb5443c5e3">|

_(Dark border indicates the edges of the preview area within Apple Mail. Please excuse the broken images 😅)_

I'd suggest wontfix for now based on low impact, and the _potential_ workaround available.
